name: Cmocka CI v2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install cmocka
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libcmocka-dev

    - name: Build and Test
      run: |
        make -C ./vm
        make test -C ./vm
        make -C ./asm
        make test -C ./asm
